"""initial schema

Revision ID: 0001
Revises:
"""
from alembic import op
import sqlalchemy as sa

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None

prospect_status = sa.Enum("NEW","TO_CONTACT","CONTACTED","INTERESTED","QUOTED","FOLLOW_UP","CUSTOMER","LOST","DO_NOT_CONTACT", name="prospect_status")
quote_status = sa.Enum("DRAFT","SENT","ACCEPTED","REJECTED","EXPIRED", name="quote_status")

def upgrade():
    prospect_status.create(op.get_bind(), checkfirst=True); quote_status.create(op.get_bind(), checkfirst=True)
    op.create_table("products", sa.Column("id",sa.Integer(),primary_key=True),sa.Column("sku",sa.String(32),nullable=False),sa.Column("category",sa.String(80),nullable=False),sa.Column("name",sa.String(160),nullable=False),sa.Column("format",sa.String(40),nullable=False),sa.Column("price_gross_clp",sa.Numeric(12,2)),sa.Column("active",sa.Boolean(),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False),sa.UniqueConstraint("sku"))
    op.create_index("ix_products_sku","products",["sku"],unique=True); op.create_index("ix_products_category","products",["category"]); op.create_index("ix_products_name","products",["name"])
    op.create_table("prospects", sa.Column("id",sa.Integer(),primary_key=True),sa.Column("company_name",sa.String(180),nullable=False),sa.Column("branch_name",sa.String(160)),sa.Column("industry",sa.String(120)),sa.Column("subindustry",sa.String(120)),sa.Column("address",sa.String(240)),sa.Column("commune",sa.String(100)),sa.Column("city",sa.String(100)),sa.Column("latitude",sa.Float()),sa.Column("longitude",sa.Float()),sa.Column("phone",sa.String(80)),sa.Column("whatsapp",sa.String(80)),sa.Column("email",sa.String(180)),sa.Column("instagram",sa.String(180)),sa.Column("website",sa.String(240)),sa.Column("google_place_id",sa.String(180),unique=True),sa.Column("source",sa.String(120)),sa.Column("source_url",sa.String(500)),sa.Column("status",prospect_status,nullable=False),sa.Column("potential",sa.String(30)),sa.Column("owner",sa.String(120)),sa.Column("notes",sa.Text()),sa.Column("last_contact_at",sa.DateTime()),sa.Column("next_action_at",sa.DateTime()),sa.Column("created_at",sa.DateTime(),nullable=False),sa.Column("updated_at",sa.DateTime(),nullable=False))
    for name,col in [("company_name","company_name"),("industry","industry"),("commune","commune"),("city","city"),("phone","phone"),("email","email"),("status","status"),("next_action_at","next_action_at"),("created_at","created_at")]: op.create_index(f"ix_prospects_{name}","prospects",[col])
    op.create_index("ix_prospect_geo","prospects",["commune","industry"])
    op.create_table("contacts",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("prospect_id",sa.Integer(),sa.ForeignKey("prospects.id",ondelete="CASCADE"),nullable=False),sa.Column("name",sa.String(160),nullable=False),sa.Column("role",sa.String(120)),sa.Column("phone",sa.String(80)),sa.Column("email",sa.String(180)),sa.Column("instagram",sa.String(180)),sa.Column("notes",sa.Text())); op.create_index("ix_contacts_prospect_id","contacts",["prospect_id"])
    op.create_table("activities",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("prospect_id",sa.Integer(),sa.ForeignKey("prospects.id",ondelete="CASCADE"),nullable=False),sa.Column("activity_type",sa.String(60),nullable=False),sa.Column("happened_at",sa.DateTime(),nullable=False),sa.Column("result",sa.Text()),sa.Column("next_action",sa.String(240)),sa.Column("next_action_at",sa.DateTime())); op.create_index("ix_activities_prospect_id","activities",["prospect_id"]); op.create_index("ix_activities_activity_type","activities",["activity_type"]); op.create_index("ix_activities_happened_at","activities",["happened_at"]); op.create_index("ix_activities_next_action_at","activities",["next_action_at"])
    op.create_table("quotes",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("quote_number",sa.String(32),unique=True),sa.Column("prospect_id",sa.Integer(),sa.ForeignKey("prospects.id"),nullable=False),sa.Column("quote_date",sa.Date(),nullable=False),sa.Column("valid_until",sa.Date(),nullable=False),sa.Column("status",quote_status,nullable=False),sa.Column("notes",sa.Text()),sa.Column("terms",sa.Text(),nullable=False),sa.Column("net_clp",sa.Numeric(14,2),nullable=False),sa.Column("tax_clp",sa.Numeric(14,2),nullable=False),sa.Column("total_clp",sa.Numeric(14,2),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False),sa.Column("sent_at",sa.DateTime())); op.create_index("ix_quotes_quote_number","quotes",["quote_number"],unique=True); op.create_index("ix_quotes_prospect_id","quotes",["prospect_id"]); op.create_index("ix_quotes_valid_until","quotes",["valid_until"]); op.create_index("ix_quotes_status","quotes",["status"])
    op.create_table("quote_items",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("quote_id",sa.Integer(),sa.ForeignKey("quotes.id",ondelete="CASCADE"),nullable=False),sa.Column("product_id",sa.Integer(),sa.ForeignKey("products.id"),nullable=False),sa.Column("product_name_snapshot",sa.String(180),nullable=False),sa.Column("quantity_kg",sa.Numeric(12,3),nullable=False),sa.Column("unit_price_gross_clp",sa.Numeric(12,2),nullable=False),sa.Column("line_total_gross_clp",sa.Numeric(14,2),nullable=False)); op.create_index("ix_quote_items_quote_id","quote_items",["quote_id"]); op.create_index("ix_quote_items_product_id","quote_items",["product_id"])
    op.create_table("orders",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("order_number",sa.String(32),unique=True),sa.Column("prospect_id",sa.Integer(),sa.ForeignKey("prospects.id"),nullable=False),sa.Column("quote_id",sa.Integer(),sa.ForeignKey("quotes.id")),sa.Column("order_date",sa.Date(),nullable=False),sa.Column("status",sa.String(60),nullable=False),sa.Column("notes",sa.Text()),sa.Column("total_gross_clp",sa.Numeric(14,2),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False)); op.create_index("ix_orders_order_number","orders",["order_number"],unique=True); op.create_index("ix_orders_prospect_id","orders",["prospect_id"]); op.create_index("ix_orders_quote_id","orders",["quote_id"]); op.create_index("ix_orders_order_date","orders",["order_date"]); op.create_index("ix_orders_status","orders",["status"])
    op.create_table("order_items",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("order_id",sa.Integer(),sa.ForeignKey("orders.id",ondelete="CASCADE"),nullable=False),sa.Column("product_id",sa.Integer(),sa.ForeignKey("products.id"),nullable=False),sa.Column("product_name_snapshot",sa.String(180),nullable=False),sa.Column("quantity_kg",sa.Numeric(12,3),nullable=False),sa.Column("unit_price_gross_clp",sa.Numeric(12,2),nullable=False),sa.Column("line_total_gross_clp",sa.Numeric(14,2),nullable=False)); op.create_index("ix_order_items_order_id","order_items",["order_id"]); op.create_index("ix_order_items_product_id","order_items",["product_id"])
    op.create_table("web_sources",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("prospect_id",sa.Integer(),sa.ForeignKey("prospects.id",ondelete="CASCADE"),nullable=False),sa.Column("source_type",sa.String(80),nullable=False),sa.Column("url",sa.String(500)),sa.Column("captured_at",sa.DateTime(),nullable=False),sa.Column("data_json",sa.Text())); op.create_index("ix_web_sources_prospect_id","web_sources",["prospect_id"])

def downgrade():
    for t in ["web_sources","order_items","orders","quote_items","quotes","activities","contacts","prospects","products"]: op.drop_table(t)
    quote_status.drop(op.get_bind(), checkfirst=True); prospect_status.drop(op.get_bind(), checkfirst=True)
